export const GET_LOCATIONS_REQUESTED = "GET_LOCATIONS_REQUESTED";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILED = "GET_LOCATIONS_FAILED";

export const POST_LOCATIONS_REQUEST = "POST_LOCATIONS_REQUEST";
export const POST_LOCATIONS_SUCCESS = "POST_LOCATIONS_SUCCESS";
export const POST_LOCATIONS_FAILED = "POST_LOCATIONS_FAILED";

export const DELETE_LOCATIONS_REQUEST = "DELETE_LOCATIONS_REQUEST";
export const DELETE_LOCATIONS_SUCCESS = "DELETE_LOCATIONS_SUCCESS";
export const DELETE_LOCATIONS_FAILED = "DELETE_LOCATIONS_FAILED";

export const ADD_DATA = "ADD_DATA";
